language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux

services:
  - docker

branches:
  only:
    - webhook

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make artifactory-login
  - make lint

script:
  - make image
  - make push-images
