language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.9

os:
  - linux

services:
  - docker

branches:
  only:
    - 3.1.2-patch

env:
  matrix:
    - OS=rhel7 TARGET=9.42.40.115
    - OS=linux

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make artifactory-login
  
script:
  - make image
  - make push-images
