language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux
  - linux-ppc64le
  - linux-s390
services:
  - docker

branches:
  only:
    - rhel-image

env:
  matrix:
    - OS=rhel7 TARGET=9.42.99.162
    - OS=linux

matrix:
  fast_finish: true
  exclude:
  - os: linux-ppc64le
    env: OS=rhel7 TARGET=9.42.99.162
  - os: linux-s390
    env: OS=rhel7 TARGET=9.42.99.162


before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make artifactory-login

script:
  - make image
  - make push-images
