language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-harness

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

stages:
  - lint
  - test
  - build
  - publish

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      script:
        - make go-fmt
        - make go-test
    - stage: build
      script:
        - make init
        - make image
    - stage: publish
      script:
        - make docker:login
        - make push-images
