language: go

go_import_path: github.com/jetstack/cert-manager

go:
  - 1.9

os:
  - linux
  - linux-ppc64le

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - docker-repo-change

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make docker-login
  - make manifest-tool

script:
  - make image
  - make release-all
  - make multi-arch-all
  
after_success:
  - echo "Travis event type  $TRAVIS_EVENT_TYPE"
  - echo "Travis branch $TRAVIS_BRANCH"
  - echo "Build leader  $BUILD_LEADER"
  - echo "Build aggregate status $BUILD_AGGREGATE_STATUS"

