language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux

services:
  - docker

branches:
  only:
    - rhel-certification

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make artifactory-login

script:
  - make image
  - make push-images
  - |
      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
        make rhel-images
      fi
  