language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-harness

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

before_script:
  - make init

stages:
  - lint
  - test
  - build
  - publish

jobs:
  include:
    - stage: lint
      name: "source code"
      script:
        - make -s lint
    - stage: test
      name: "run go-fmt"
      os: linux
      script:
        - make -s go-fmt
    - stage: test
      name: "run unit tests"
      os: linux
      script:
        - make -s go-test
    - stage: build
      name: "build go binary"
      script:
        - make -s build-go
    - stage: build
      name: "build docker images"
      os: linux
      script:
        - make -s build-images
    - stage: build
      name: "build docker images"
      os: linux-ppc64le
      script:
        - make -s build-images
    - stage: build
      name: "build docker images"
      os: linux-s390x
      script:
        - make -s build-images
    - stage: publish
      name: "push images to remote repo"
      script:
        - make docker:login
        - make -s push-images
