language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.9

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - 0.7.0

env:
  matrix:
    - OS=rhel7 TARGET=9.42.99.162
    - OS=linux

matrix:
  fast_finish: true
  exclude:
  - os: linux-ppc64le
    env: OS=rhel7 TARGET=9.42.99.162
  - os: linux-s390
    env: OS=rhel7 TARGET=9.42.99.162

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make artifactory-login
  - make lint

script:
  - make image
  - |
      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
        make go-test
        echo "testing complete"
        make go-fmt
        echo "go fmt complete"
      fi
  - make push-images

after_success:
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" != "others_succeeded" ]]; then
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi
