language: bash
sudo: true
group: legacy

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-harness

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make init
  - make docker:login
  - make lint

script:
  - make build
  - make push-images
