language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-harness

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make init
  - make docker:login
  - make lint

script:
  - make build
  - |
    if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
      make go-test
      echo "testing complete"
      make go-fmt
      echo "go fmt complete"
    fi
  - |
      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
        make rhel-images
      fi
  - make push-images
  
after_success:
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" != "others_succeeded" ]]; then
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi
