language: go

go_import_path: github.com/jetstack/cert-manager

go:
  - 1.9

os:
  - linux
  - linux-ppc64le

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  matrix:
    - OS=rhel7 TARGET=9.42.40.115
    - OS=linux

matrix:
  fast_finish: true
  exclude:
  - os: linux-ppc64le
    env: OS=rhel7 TARGET=9.42.40.115

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make docker-login
  - make artifactory-login
  - make lint

script:
  - make image
  - |
      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "linux-s390" ]]; then
        make go-verify
      fi
  - make docker-push-images

after_success:
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release-all || echo "success"
  - |
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
        python travis_after_all.py https://travis.ibm.com/api
        export $(cat .to_export_back)
        if [[ "$BUILD_LEADER" == "YES" ]]; then
          if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
          else
            echo "Some jobs failed" && exit 1
          fi
        fi
      fi

