language: bash
sudo: true

language: go
go_import_path: github.com/jetstack/cert-manager
go:
  - 1.12

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-harness

matrix:
  fast_finish: true

before_install:
  - source travis-env.sh

stages:
  - lint
  - test
  - build
  - publish

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      os: linux
      script:
        - make go-fmt
        - make go-test              
    - stage: build
      os: linux
      script:
        - make init
        - make image
    - stage: build
      os: linux-ppc64le
      script:
        - make init
        - make image
    - stage: build
      os: linux-s390x
      script:
        - make init
        - make image
    - stage: publish
      os: linux
      script:
        - make docker:login
        - make push-images
    - stage: publish
      os: linux-ppc64le
      script:
        - make docker:login
        - make push-images
    - stage: publish
      os: linux-s390x
      script:
        - make docker:login
        - make push-images
