language: go

go_import_path: github.com/jetstack/cert-manager

go:
  - 1.9

os:
  - linux
  - linux-ppc64le

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - build-cleanup

env:
  matrix:
    - OS=rhel7 TARGET=9.42.40.115
    - OS=linux

matrix:
  fast_finish: true
  exclude:
  - os: linux-ppc64le
    env: OS=rhel7 TARGET=9.42.40.115

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tunnel
  - make docker-login
  - make artifactory-login
  - make lint

script:
  - make image
  - make push-images

